import { imageSrc } from "@/lib/image";
import { motion } from "framer-motion";
import { ArrowUpRight, Instagram } from "lucide-react";
import { Link } from "@/lib/navigation";
import { projects } from "@/data/projectsData";

const FeaturedWork = () => { const web = projects.filter((p) => p.type === "web").slice(0, 3); const social = projects.filter((p) => p.type === "social").slice(0, 1)[0]; return <section className="relative overflow-hidden bg-white py-24 lg:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-10"><div className="mb-14 flex flex-col gap-6 border-b border-border pb-8 md:flex-row md:items-end md:justify-between"><div><p className="mb-5 text-xs font-semibold uppercase tracking-[.24em] text-cyan">Selected work</p><h2 className="max-w-xl text-4xl font-semibold leading-[.95] tracking-[-.06em] md:text-6xl">Work that earns attention.</h2></div><Link to="/portfolio" className="inline-flex items-center gap-2 text-sm font-semibold text-foreground">View all work <ArrowUpRight className="h-4 w-4 text-cyan" /></Link></div><div className="grid gap-5 lg:grid-cols-12">{web.map((project, index) => <ProjectCard key={project.id} project={project} index={`0${index + 1}`} featured={index === 0} />)}{social && <SocialCard project={social} />}</div></div></section>; };

const ProjectCard = ({ project, index, featured }: { project: (typeof projects)[0]; index: string; featured?: boolean }) => <Link to={`/portfolio/${project.slug}`} className={`group ${featured ? "lg:col-span-7 lg:row-span-2" : "lg:col-span-5"}`}><motion.article whileHover={{ y: -5 }} className={`relative h-full min-h-[300px] overflow-hidden rounded-[1.5rem] border border-border bg-muted ${featured ? "lg:min-h-[560px]" : "lg:min-h-[270px]"}`}><img src={imageSrc(project.image)} alt={project.title} className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/10 to-transparent" /><div className="relative flex h-full flex-col justify-between p-6 lg:p-8"><div className="flex items-center justify-between text-xs font-medium text-white/75"><span>{index} / {project.category}</span><ArrowUpRight className="h-5 w-5 text-cyan" /></div><div><h3 className={`${featured ? "text-4xl lg:text-5xl" : "text-2xl"} max-w-xl font-semibold leading-[.95] tracking-[-.05em] text-white`}>{project.title}</h3><p className="mt-3 max-w-md text-sm leading-relaxed text-white/70">{project.description}</p></div></div></motion.article></Link>;

const SocialCard = ({ project }: { project: (typeof projects)[0] }) => { const gallery = (project as any).gallery ?? [project.image]; return <Link to={`/portfolio/${project.slug}`} className="group lg:col-span-5"><motion.article whileHover={{ y: -5 }} className="grid min-h-[270px] h-full overflow-hidden rounded-[1.5rem] border border-border bg-muted lg:grid-cols-[1.1fr_.9fr]"><div className="grid grid-cols-2 gap-1 overflow-hidden">{gallery.slice(0, 2).map((img: string, i: number) => <img key={i} src={imageSrc(img)} alt="" className="h-full w-full object-cover transition duration-700 group-hover:scale-105" />)}</div><div className="flex flex-col justify-between p-6"><div className="flex items-center justify-between"><Instagram className="h-4 w-4 text-cyan" /><ArrowUpRight className="h-4 w-4 text-cyan" /></div><div><span className="text-xs font-semibold uppercase tracking-wider text-cyan">Social / Content kit</span><h3 className="mt-2 text-xl font-semibold tracking-tight text-foreground">{project.title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{project.description}</p></div></div></motion.article></Link>; };

export default FeaturedWork;
