import { motion } from "framer-motion";
import { ArrowUpRight, Compass, Layers3, TrendingUp } from "lucide-react";
import { Link } from "@/lib/navigation";

const practiceAreas = [
  { number: "01", icon: Compass, title: "Positioning & direction", description: "Clarify what you do, who it is for, and why it matters before we make anything.", deliverables: ["Positioning", "Messaging", "Site structure"] },
  { number: "02", icon: Layers3, title: "Websites & digital systems", description: "Turn attention into action with a site or product that feels easy to use.", deliverables: ["Websites", "E-commerce", "Booking systems"] },
  { number: "03", icon: TrendingUp, title: "Launch & improve", description: "Keep the system useful after launch with focused support, SEO, and measurement.", deliverables: ["SEO", "Conversion", "Analytics"] },
];

const ServicesPreview = () => <section className="relative overflow-hidden bg-muted/35 py-24 lg:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-10"><div className="mb-14 grid gap-6 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="mb-5 text-xs font-semibold uppercase tracking-[.24em] text-cyan">What we do</p><h2 className="max-w-2xl text-4xl font-semibold leading-[.95] tracking-[-.06em] md:text-6xl">A better digital presence starts with clarity.</h2></div><p className="max-w-md border-t border-border pt-5 text-base leading-relaxed text-muted-foreground">We plan, design, build, and improve digital experiences that help people understand and trust your business.</p></div><div className="grid gap-4 lg:grid-cols-3">{practiceAreas.map((area, index) => <motion.article key={area.number} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .08 }} className="group rounded-[1.5rem] border border-border bg-white p-7 shadow-[0_12px_40px_hsl(222_47%_11%/.04)] transition duration-300 hover:-translate-y-1 hover:border-cyan/50 hover:shadow-[0_18px_45px_hsl(222_47%_11%/.09)] lg:p-8"><div className="mb-14 flex items-center justify-between"><span className="text-sm font-semibold text-cyan">{area.number}</span><div className="flex h-11 w-11 items-center justify-center rounded-xl border border-cyan/25 bg-cyan/5 text-cyan"><area.icon className="h-5 w-5" /></div></div><h3 className="text-2xl font-semibold tracking-tight text-foreground">{area.title}</h3><p className="mt-4 leading-relaxed text-muted-foreground">{area.description}</p><ul className="mt-7 space-y-2">{area.deliverables.map((item) => <li key={item} className="text-sm text-foreground/70">{item}</li>)}</ul><Link to="/services" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-foreground transition group-hover:gap-3">See what we do <ArrowUpRight className="h-4 w-4 text-cyan" /></Link></motion.article>)}</div></div></section>;

export default ServicesPreview;
